image: jangrewe/gitlab-ci-android

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - build
  - test

lintDebug:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew -Pci --console=plain :presentation:lintDebug -PbuildDir=lint

ktlint:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew -Pci --console=plain ktlint

assembleDebug:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew assembleDebug

testDebug:
  stage: test
  tags:
    - docker
  script:
    - ./gradlew -Pci --console=plain clean :domain:testDebug :presentation:testDebug :data:testDebug