image: jangrewe/gitlab-ci-android

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: "$CI_PIPELINE_ID"
  paths:
    - .gradle/
    - presentation

stages:
  - build
  - test
  - publish

lintDebug:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew -Pci --console=plain :presentation:lintDebug -PbuildDir=lint

ktlint:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew -Pci --console=plain ktlint

assembleDebug:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew assembleDebug

testDebug:
  stage: test
  tags:
    - docker
  script:
    - ./gradlew -Pci --console=plain clean :domain:testDebug :presentation:testDebug :data:testDebug

publishAPK:
  stage: publish
  tags:
    - docker
  script:
    - cp presentation/build/outputs/apk/debug/presentation-debug.apk .
  environment:
    name: master
  artifacts:
    name: "linshare-apk-master"
    expire_in: 1 month
    paths:
      - presentation-debug.apk
  only:
    - master